Repository Renater/SimpleScaleVM, pull requests merged in 2022-07, with the labels that each got.

#6 Add basic CI
  .github/workflows/push-workflow.yml
  .github/workflows/release-workflow.yml
  .pylintrc
Labels: enhancement

#7 External address support
  .env.template
  README.md
  src/main.py
  src/providers/imports.py
  src/providers/main.py
  src/providers/openstack/main.py
  src/providers/openstack/settings.py
  src/providers/replica.py
  src/providers/schema.py
  src/scheduler/service.py
  src/settings.py
Labels: documentation, enhancement

#8 Add documentation
  README.md
  docs/dockerhub.description.md
  docs/dockerhub.readme.md
  docs/external_addresses.png
  docs/infrastructure.png
  docs/resources.png
  docs/simplescalevm-in-depth.md
Labels: documentation

#9 Add the Autoscaling feature
  .env.template
  .gitignore
  GNUmakefile
  README.md
  docker-compose.yml
  docs/dockerhub.readme.md
  src/autoscaler/main.py
  src/main.py
  src/providers/openstack/main.py
  src/providers/openstack/settings.py
  src/providers/schema.py
  src/scheduler/main.py
  src/scheduler/service.py
  src/server/launcher.py
  src/server/request_handler.py
  src/settings.py
Labels: documentation, enhancement

#10 Add autoscaling docs
  docs/autoscaling_infrastructure.png
  docs/autoscaling_master.png
  docs/simplescalevm-in-depth.md
Labels: documentation
